baseURL = 'https://linuxadminbooks.com/'
languageCode = 'en-us'
title = 'Linux Admin Books'

# Book configuration
disablePathToLower = true
enableGitInfo = true

[menu]

[[menu.before]]
  name = "Linux Admin Books"
  url = "/"
  weight = 0

[[menu.after]]
  name = "Github"
  url = "https://github.com/LinuxAdminBooks"
  weight = 10

[[menu.after]]
  name = "thepotato.tech"
  url = "https://thepotato.tech"

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'
