baseURL = 'https://linuxadminbooks.com/'
languageCode = 'en-us'
title = 'Linux Admin Books'

# Book configuration
disablePathToLower = true
enableGitInfo = truwe

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/LinuxAdminBooks"
  weight = 10

[[menu.after]]
  name = "ThePotato.Tech"
  url = "https://thepotato.tech"

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'
